#!/usr/bin/env python3
"""Build the printable nav log from src/slip.html + src/navlog.css.

Two variants are built. They differ only in how the same 119.8 mm of nav
table is divided up — more legs with tighter rows, or fewer legs with rows
you can actually write in on a bumpy day. Everything else, the outer size
included, is identical, so a printed pair is a fair comparison.

Emits, into build/, for each variant:

  navlog-<tag>.html                  self-contained page (CSS inlined) — also
                                     prints acceptably straight from a browser
  NavLog-A4-3up-<tag>.pdf            duplex, flip on SHORT edge
  NavLog-A4-3up-<tag>-longedge.pdf   same, back page pre-rotated 180 degrees,
                                     for printers whose duplex is the other way

SPDX-License-Identifier: CC0-1.0
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
BUILD = ROOT / "build"

SLIPS_PER_PAGE = 3
PAGES = 2  # front and back of the same slip

TITLE = "VFR Nav Log — kneeboard slip, 3-up on A4 landscape"


@dataclass(frozen=True)
class Variant:
    """One way of spending the nav table's fixed height.

    `tag` names the output files and is printed faintly next to the ▲ TOP
    mark, so a slip that has been cut off the sheet still says which grid it
    carries. `wprow` and `datarow` override the CSS custom properties of the
    same name; `waypoints` is how many name-plus-two-data-rows blocks are
    stamped out above the bare destination row.

    Both variants below come to the same table height:

        thead 7 + waypoints x (wprow + 2 x datarow) + wprow

    which leaves the free-text block 22.2 mm either way.
    """

    tag: str
    waypoints: int
    wprow: str
    datarow: str
    note: str


VARIANTS = (
    Variant(
        tag="7L",
        waypoints=7,
        wprow="4.3mm",
        datarow="5.6mm",
        note="seven legs, tighter rows",
    ),
    Variant(
        tag="6L",
        waypoints=6,
        wprow="4.8mm",
        datarow="6.6mm",
        note="six legs, roomier rows",
    ),
)

REPEAT_RE = re.compile(
    r"[ \t]*<!-- REPEAT:WP -->\n(.*?)[ \t]*<!-- /REPEAT:WP -->\n",
    re.DOTALL,
)


def render_slip(variant: Variant) -> str:
    """Expand the waypoint repeat block in the slip fragment."""
    fragment = (SRC / "slip.html").read_text(encoding="utf-8")
    match = REPEAT_RE.search(fragment)
    if match is None:
        sys.exit("src/slip.html: REPEAT:WP block not found")
    slip = REPEAT_RE.sub(match.group(1) * variant.waypoints, fragment)
    if "VARIANT" not in slip:
        sys.exit("src/slip.html: VARIANT placeholder not found")
    return slip.replace("VARIANT", variant.tag)


def indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in text.splitlines())


def render_html(variant: Variant) -> str:
    css = (SRC / "navlog.css").read_text(encoding="utf-8")
    slip = render_slip(variant)
    # Drop the fragment's leading maintainer comment from the generated file.
    slip = re.sub(r"^<!--.*?-->\n", "", slip, count=1, flags=re.DOTALL)

    # Appended, not substituted into the :root block, so src/navlog.css stays
    # a valid stylesheet on its own and the override is visible as an override.
    css += (
        f"\n/* --- variant {variant.tag}: {variant.note} --------------------- */\n"
        ":root {\n"
        f"  --h-wprow: {variant.wprow};\n"
        f"  --h-datarow: {variant.datarow};\n"
        "}\n"
    )

    pages = []
    for _ in range(PAGES):
        body = "\n".join(indent(slip.strip(), 6) for _ in range(SLIPS_PER_PAGE))
        pages.append('    <div class="sheet">\n' + body + "\n    </div>")

    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '  <meta charset="utf-8" />\n'
        f"  <title>{TITLE} ({variant.tag}: {variant.note})</title>\n"
        "  <!-- GENERATED by tools/build.py — edit src/slip.html and\n"
        "       src/navlog.css instead, then run `make`. -->\n"
        "  <style>\n" + indent(css, 4) + "\n  </style>\n"
        "</head>\n"
        "<body>\n" + "\n".join(pages) + "\n</body>\n"
        "</html>\n"
    )


def write_pdfs(variant: Variant, html_path: Path) -> None:
    from weasyprint import HTML

    document = HTML(filename=str(html_path)).render()

    short_edge = BUILD / f"NavLog-A4-3up-{variant.tag}.pdf"
    document.write_pdf(str(short_edge))
    print(f"  {short_edge.relative_to(ROOT)}  ({len(document.pages)} pages)")

    # Long-edge variant: same document with the back page rotated 180 degrees.
    long_edge = BUILD / f"NavLog-A4-3up-{variant.tag}-longedge.pdf"
    from pypdf import PdfReader, PdfWriter

    reader = PdfReader(str(short_edge))
    writer = PdfWriter()
    for number, page in enumerate(reader.pages):
        if number % 2 == 1:
            page.rotate(180)
        writer.add_page(page)
    with long_edge.open("wb") as handle:
        writer.write(handle)
    print(f"  {long_edge.relative_to(ROOT)}  (back page rotated 180°)")


def main() -> None:
    BUILD.mkdir(exist_ok=True)
    for variant in VARIANTS:
        print(f"{variant.tag}: {variant.note}")
        html_path = BUILD / f"navlog-{variant.tag}.html"
        html_path.write_text(render_html(variant), encoding="utf-8")
        print(f"  {html_path.relative_to(ROOT)}")
        write_pdfs(variant, html_path)


if __name__ == "__main__":
    main()
