#!/usr/bin/env python3
"""Build the printable nav log from src/slip.html + src/navlog.css.

Emits, into build/:

  navlog.html                  self-contained page (CSS inlined) — also
                               prints acceptably straight from a browser
  NavLog-A4-3up.pdf            duplex, flip on SHORT edge
  NavLog-A4-3up-longedge.pdf   same, back page pre-rotated 180 degrees, for
                               printers whose duplex option is the other way

SPDX-FileCopyrightText: Carsten Ritter
SPDX-License-Identifier: CC-BY-SA-4.0
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
BUILD = ROOT / "build"

SLIPS_PER_PAGE = 3
PAGES = 2  # front and back of the same slip
WAYPOINTS = 7

TITLE = "VFR Nav Log — kneeboard slip, 3-up on A4 landscape"

REPEAT_RE = re.compile(
    r"[ \t]*<!-- REPEAT:WP -->\n(.*?)[ \t]*<!-- /REPEAT:WP -->\n",
    re.DOTALL,
)


def render_slip() -> str:
    """Expand the waypoint repeat block in the slip fragment."""
    fragment = (SRC / "slip.html").read_text(encoding="utf-8")
    match = REPEAT_RE.search(fragment)
    if match is None:
        sys.exit("src/slip.html: REPEAT:WP block not found")
    return REPEAT_RE.sub(match.group(1) * WAYPOINTS, fragment)


def indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in text.splitlines())


def render_html() -> str:
    css = (SRC / "navlog.css").read_text(encoding="utf-8")
    slip = render_slip()
    # Drop the fragment's leading maintainer comment from the generated file.
    slip = re.sub(r"^<!--.*?-->\n", "", slip, count=1, flags=re.DOTALL)

    pages = []
    for _ in range(PAGES):
        body = "\n".join(indent(slip.strip(), 6) for _ in range(SLIPS_PER_PAGE))
        pages.append('    <div class="sheet">\n' + body + "\n    </div>")

    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '  <meta charset="utf-8" />\n'
        f"  <title>{TITLE}</title>\n"
        "  <!-- GENERATED by tools/build.py — edit src/slip.html and\n"
        "       src/navlog.css instead, then run `make`. -->\n"
        "  <style>\n" + indent(css, 4) + "\n  </style>\n"
        "</head>\n"
        "<body>\n" + "\n".join(pages) + "\n</body>\n"
        "</html>\n"
    )


def write_pdfs(html_path: Path) -> None:
    from weasyprint import HTML

    document = HTML(filename=str(html_path)).render()

    short_edge = BUILD / "NavLog-A4-3up.pdf"
    document.write_pdf(str(short_edge))
    print(f"  {short_edge.relative_to(ROOT)}  ({len(document.pages)} pages)")

    # Long-edge variant: same document with the back page rotated 180 degrees.
    long_edge = BUILD / "NavLog-A4-3up-longedge.pdf"
    from pypdf import PdfReader, PdfWriter

    reader = PdfReader(str(short_edge))
    writer = PdfWriter()
    for number, page in enumerate(reader.pages):
        if number % 2 == 1:
            page.rotate(180)
        writer.add_page(page)
    with long_edge.open("wb") as handle:
        writer.write(handle)
    print(f"  {long_edge.relative_to(ROOT)}  (back page rotated 180°)")


def main() -> None:
    BUILD.mkdir(exist_ok=True)
    html_path = BUILD / "navlog.html"
    html_path.write_text(render_html(), encoding="utf-8")
    print(f"  {html_path.relative_to(ROOT)}")
    write_pdfs(html_path)


if __name__ == "__main__":
    main()
